<?php

namespace AppBundle\Repository;

/**
 * AttributesProjectSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributesProjectSettingsRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateStatus($id, $status){

        $this->getEntityManager()
            ->createQueryBuilder()
            ->update('AppBundle:AttributesProjectSettings', 'ad')
            ->set('ad.isEnable', ':st')
            ->where('ad.id = :id')
            ->setParameter('id', $id)
            ->setParameter('st', $status)
            ->getQuery()->execute()
        ;
    }

    /*public function updateOrdering($name){

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ad, attr')
            ->from('AppBundle:AttributesProjectSettings', 'ad')
            ->leftJoin('ad.attributesDefinition', 'attr')
            ->where('attr.attrName = :nm')
            ->setParameter('nm', $name)
            ->getQuery()->getResult()
            ;
    }*/

    /**
     * @param $label
     * @param $objectName
     * @param $belongsToObject
     */
    public function updateOrdering($oldSortOrdering, $sortOrdering, $attrId){

        $this->getEntityManager()
            ->createQueryBuilder()
            ->update('AppBundle:AttributesProjectSettings', 'cv')
            ->set('cv.sortOrdering', ':lb')
            ->where('cv.sortOrdering = :oldLb')
            ->andWhere('cv.belongsToObject = :objid')
            ->setParameter('lb', $sortOrdering)
            ->setParameter('oldLb', $oldSortOrdering)
            ->setParameter('objid', $attrId)
            ->getQuery()->execute()
        ;
    }
}
