<?php

namespace AppBundle\Repository;

/**
 * AttributesPageSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributesPageSettingsRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateStatus($id, $status){

        $this->getEntityManager()
            ->createQueryBuilder()
            ->update('AppBundle:AttributesPageSettings', 'ad')
            ->set('ad.isEnable', ':st')
            ->where('ad.id = :id')
            ->setParameter('id', $id)
            ->setParameter('st', $status)
            ->getQuery()->execute()
        ;
    }
}
