<?php

namespace AppBundle\Repository;

/**
 * BooleanValuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BooleanValuesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $label
     * @param $objectName
     * @param $belongsToObject
     */
    public function updateByAttributesDefinition($oldLabel, $label, $objectName){

        $this->getEntityManager()
            ->createQueryBuilder()
            ->update('AppBundle:BooleanValues', 'cv')
            ->set('cv.title', ':lb')
            ->where('cv.title = :oldLb')
//            ->andWhere('cv.belongsToObject = :objid')
            ->setParameter('lb', $label)
            ->setParameter('oldLb', $oldLabel)
//            ->setParameter('objid', $belongsToObject)
            ->getQuery()->execute()
        ;
    }

    /**
     * Update sort order
     *
     * @param $attrId
     * @param $sortOrdering
     * @param $oldSortOrdering
     */
    public function updateOrdering($oldSortOrdering, $sortOrdering, $attrId) {

        $this->getEntityManager()
            ->createQueryBuilder()
            ->update('AppBundle:BooleanValues', 'cv')
            ->set('cv.sortOrdering', ':lb')
            ->where('cv.title = :oldLb')
            ->andWhere('cv.belongsToObject = :objid')
            ->setParameter('lb', $sortOrdering)
            ->setParameter('oldLb', $oldSortOrdering)
            ->setParameter('objid', $attrId)
            ->getQuery()->execute()
        ;
    }
}
