<?php

namespace AppBundle\Repository;

/**
 * BooleanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BooleanRepository extends \Doctrine\ORM\EntityRepository
{

}
