<?php

namespace AppBundle\Repository;

/**
 * CampaignSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
