<?php

namespace AppBundle\Repository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPage($itemId, $slug){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('f')
            ->from('AppBundle:File', 'f')
            ->join('f.item', 'i')
            ->where('i.id = :iid')
            ->andWhere('f.slug = :fslug')
            ->setParameter('iid', $itemId)
            ->setParameter('fslug', $slug)
            ->getQuery()->getOneOrNullResult()
            ;
    }

    /**
     * This function use to get by belobg to object
     */
    public function findByObject($obgId, $title = null){

        $q = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('i')
            ->from('AppBundle:File', 'i')
            ->where('i.belongsToObjectId = :onjId');

        if (!is_null($title)){
            $q->
            andWhere('i.title = :it')
                ->setParameter('onjId', $obgId)
                ->setParameter('it', $title)
                ->getQuery()->getOneOrNullResult()
            ;
        }else {
            $q    ->setParameter('onjId', $obgId)
                ->getQuery()->getResult();
        }



    }

    /**
     * @param $label
     * @param $objectName
     * @param $belongsToObject
     */
    public function updateByAttributesDefinition($oldLabel, $label, $objectName){

        $this->getEntityManager()
            ->createQueryBuilder()
            ->update('AppBundle:File', 'cv')
            ->set('cv.title', ':lb')
            ->where('cv.title = :oldLb')
            ->setParameter('lb', $label)
            ->setParameter('oldLb', $oldLabel)
            ->getQuery()->execute()
        ;
    }


    /**
     * Update sort order
     *
     * @param $attrId
     * @param $sortOrdering
     * @param $oldSortOrdering
     */
    public function updateOrdering($oldSortOrdering, $sortOrdering, $attrId){

        $this->getEntityManager()
            ->createQueryBuilder()
            ->update('AppBundle:File', 'cv')
            ->set('cv.sortOrdering', ':lb')
            ->where('cv.title = :oldLb')
            ->andWhere('cv.belongsToObject = :objid')
            ->setParameter('lb', $sortOrdering)
            ->setParameter('oldLb', $oldSortOrdering)
            ->setParameter('objid', $attrId)
            ->getQuery()->execute()
        ;
    }
}
