<?php

namespace AppBundle\Repository;

use AppBundle\Entity\AttributesDefinition;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
        public function findDataById($objectId){
            return $this->getEntityManager()
                ->createQueryBuilder()
                ->select('cmp, settings')
                ->from('AppBundle:Page', 'cmp')
                ->leftJoin('cmp.settings', 'settings')
                ->where('cmp.id = :cId')
                ->orderBy('cmp.id')
                ->addOrderBy('settings.sortOrdering')
                ->setParameter('cId', $objectId)
                ->getQuery()
                ->getResult();

        }

    /**
     * This repo use for get page by slug
     * Slug is not editable
     *
     * @param $slug
     * @return array
     */
    public function findForShow($slug) {

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('cmp, settings, attributesDefinition')
            ->from('AppBundle:Page', 'cmp')
            ->leftJoin('cmp.settings', 'settings')
            ->leftJoin('settings.attributesDefinition', 'attributesDefinition')
            ->where('cmp.slug = :slg')
            ->andWhere('settings.isEnable = :status')
            ->setParameter('slg', $slug)
            ->setParameter('status', 1)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
