<?php

namespace AppBundle\Repository;

/**
 * TextValuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextValuesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * This function use to get by belobg to object
     */
    public function findByObject($obgId, $title = null){

        $q = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('i')
            ->from('AppBundle:TextValues', 'i')
            ->where('i.belongsToObjectId = :onjId');

        if (!is_null($title)){
            $q->
            andWhere('i.title = :it')
                ->setParameter('onjId', $obgId)
                ->setParameter('it', $title)
                ->getQuery()->getOneOrNullResult()
            ;
        }else {
            $q    ->setParameter('onjId', $obgId)
                ->getQuery()->getResult();
        }




    }

    /**
     * @param $label
     * @param $objectName
     * @param $belongsToObject
     */
    public function updateByAttributesDefinition($oldLabel, $label, $attrId){

        $this->getEntityManager()
            ->createQueryBuilder()
            ->update('AppBundle:TextValues', 'cv')
            ->set('cv.title', ':lb')
            ->where('cv.title = :oldLb')
            ->andWhere('cv.belongsToObject = :objid')
            ->setParameter('lb', $label)
            ->setParameter('oldLb', $oldLabel)
            ->setParameter('objid', $attrId)
            ->getQuery()->execute()
        ;
    }

    /**
     * @param $label
     * @param $objectName
     * @param $belongsToObject
     */
    public function updateOrdering($oldSortOrdering, $sortOrdering, $attrId){

        $this->getEntityManager()
            ->createQueryBuilder()
            ->update('AppBundle:TextValues', 'cv')
            ->set('cv.sortOrdering', ':lb')
            ->where('cv.title = :oldLb')
            ->andWhere('cv.belongsToObject = :objid')
            ->setParameter('lb', $sortOrdering)
            ->setParameter('oldLb', $oldSortOrdering)
            ->setParameter('objid', $attrId)
            ->getQuery()->execute()
        ;
    }
}
