# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

# Attr Defin Event Listiner
        attrdef.data.event.listener:
              class: AppBundle\DoctrineListeners\EventListener
              arguments: ['@service_container']
              tags:
                   - { name: doctrine.event_listener, event: onFlush }

        app.calculat.values:
              class: AppBundle\Service\CalculateValues
              arguments: ['@service_container']

#        app.attributes.definition.service:
#              class: AppBundle\Service\AttributesDefinitionService
#              arguments: ['@service_container']

        app.classy.api:
              class: AppBundle\Service\ClassyApi
              arguments: ['@service_container']

        app.calculate.list.values:
              class: AppBundle\Service\ListValues
              arguments: ['@service_container']

        app.form.type.gender:
              class: AppBundle\Form\IconType
              tags:
                  - { name: form.type, alias: icon_type }

        app.form.type.text.simple:
              class: AppBundle\Form\TextSimpleType
              tags:
                  - { name: form.type, alias: text_simple_type }

        app.form.type.list.text:
              class: AppBundle\Form\TextListType
              tags:
                  - { name: form.type, alias: app_bundle_text_list }

        app.form.type.list.boolean:
              class: AppBundle\Form\BooleanListType
              tags:
                  - { name: form.type, alias: app_bundle_boolean_list }

        app.form.type.list.listing:
              class: AppBundle\Form\ListingListType
              tags:
                  - { name: form.type, alias: app_bundle_listing_list }

        app.form.type.date.text:
              class: AppBundle\Form\DateListType
              tags:
                  - { name: form.type, alias: app_bundle_date_list }

        app.form.type.parent.info:
              class: AppBundle\Form\ParentInfoListType
              tags:
                  - { name: form.type, alias: app_bundle_parent_info_list }

        app.form.type.list.file:
              class: AppBundle\Form\FileListType
              tags:
                  - { name: form.type, alias: app_bundle_file_list_type }

        app.form.type.list.image:
              class: AppBundle\Form\ImageListType
              tags:
                  - { name: form.type, alias: app_bundle_image_list_type }

        app.form.type.campaign.values:
              class: AppBundle\Form\CampaignValuesType
              arguments: ['@doctrine.orm.entity_manager']
              tags:
                  - { name: form.type, alias: campaign_values_type }

        sonata.admin.block.project.list:
                class: AppBundle\Block\CustomMosaicAdminBlock
                arguments:
                    - "Admin Projects List"
                    - "@templating"
                    - "@sonata.admin.pool"
                tags:
                    - { name: sonata.block }

        app.admin.user:
              class: AppBundle\Admin\UserAdmin
              arguments: [~, AppBundle\Entity\User, SonataAdminBundle:CRUD]
              tags:
                  - {name: sonata.admin, manager_type: orm, group: User, label: User, show_in_dashboard: false }

#        sonata.admin.campaign:
#              class: AppBundle\Admin\CampaignAdmin
#              arguments: [~, AppBundle\Entity\Campaign, AppBundle:Admin, ~]
#              tags:
#                  - {name: sonata.admin, manager_type: orm, group: Menu, label: Campaign, show_in_dashboard: true}
#
#        sonata.admin.project:
#              class: AppBundle\Admin\ProjectAdmin
#              arguments: [~, AppBundle\Entity\Project, AppBundle:Admin, ~]
#              tags:
#                  - {name: sonata.admin, manager_type: orm, group: Menu, label: Projects, show_in_dashboard: true}
#
#        sonata.admin.campaign.settings:
#              class: AppBundle\Admin\AttributesCampaignSettingsAdmin
#              arguments: [~, AppBundle\Entity\AttributesCampaignSettings, AppBundle:Admin, ~]
#              tags:
#                  - {name: sonata.admin, manager_type: orm, group: Documents, label: Campaign Settings, show_in_dashboard: true }

#        sonata.admin.project.settings:
#              class: AppBundle\Admin\AttributesProjectSettingsAdmin
#              arguments: [~, AppBundle\Entity\AttributesProjectSettings, AppBundle:Admin, ~]
#              tags:
#                  - {name: sonata.admin, manager_type: orm, group: Documents, label: Project Settings, show_in_dashboard: true }

        sonata.admin.page:
              class: AppBundle\Admin\PageAdmin
              arguments: [~, AppBundle\Entity\Page, AppBundle:Admin, ~]
              tags:
                  - {name: sonata.admin, manager_type: orm, group: Menu, label: Pages, show_in_dashboard: true }

        sonata.admin.page.settings:
              class: AppBundle\Admin\AttributesPageSettingsAdmin
              arguments: [~, AppBundle\Entity\AttributesPageSettings, AppBundle:Admin, ~]
              tags:
                  - {name: sonata.admin, manager_type: orm, group: Documents, label: Page Settings, show_in_dashboard: true }

        sonata.admin.list.settings:
              class: AppBundle\Admin\AttributesListSettingsAdmin
              arguments: [~, AppBundle\Entity\AttributesListSettings, AppBundle:Admin, ~]
              tags:
                  - {name: sonata.admin, manager_type: orm, group: Documents, label: List Settings, show_in_dashboard: true }

        sonata.admin.attributes.definition:
              class: AppBundle\Admin\AttributesDefinitionAdmin
              arguments: [~, AppBundle\Entity\AttributesDefinition, AppBundle:Admin, ~]
              tags:
                  - {name: sonata.admin, manager_type: orm, group: Documents, label: Attributes Definition, show_in_dashboard: true }

        sonata.admin.collection.values:
              class: AppBundle\Admin\CollectionValuesAdmin
              arguments: [~, AppBundle\Entity\CollectionValues, AppBundle:Admin, ~]
              tags:
                  - {name: sonata.admin, manager_type: orm, group: Documents, label: Collection, show_in_dashboard: true }

        sonata.admin.attributes.list:
              class: AppBundle\Admin\ListValuesAdmin
              arguments: [~, AppBundle\Entity\ListValues, AppBundle:Admin, ~]
              tags:
                  - {name: sonata.admin, manager_type: orm, group: Documents, label: Attribute List, show_in_dashboard: true }
        sonata.admin.text.values:
              class: AppBundle\Admin\TextAdmin
              arguments: [~, AppBundle\Entity\TextValues, AppBundle:Admin, ~]
              tags:
                  - {name: sonata.admin, manager_type: orm, group: Documents, label: Texts, show_in_dashboard: true }

        app.image_filter.twig_extension:
              class: AppBundle\Twig\Extension\ImageFilterExtension
              arguments: [ @service_container ]
              tags:
                  - { name: twig.extension }

        twig.extension.sortbyfield:
                class: AppBundle\Twig\Extension\SortByFieldExtension
                tags:
                    - { name: twig.extension }
